//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ArNTClassifierConsole.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ARNTCLASSIFIERCONSOLE_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_SAMPLE_COLLECTION    129
#define IDD_DIALOG_CLASSIFIER           130
#define IDD_DIALOG_DEFECTCLASS          131
#define IDD_DIALOG_DEFECTCLASSIFY       131
#define IDI_ICON1                       132
#define IDI_ICON2                       133
#define IDI_ICON3                       134
#define IDI_ICON4                       135
#define IDI_ICON5                       136
#define IDR_MENU_ADD_DEFECT             138
#define IDB_PNG_LOGO                    141
#define IDB_BITMAP_LOGO                 142
#define IDD_DIALOG_CLASSIFIER_BP        143
#define IDD_DIALOG_CLASSIFIER_SVM       144
#define IDD_DIALOG_CLASSIFIER_TREE      145
#define IDD_DIALOG_CLASSIFIER_BOOSTING  146
#define IDD_DIALOG_CLASSIFIER_CNN       147
#define IDD_DIALOG1                     148
#define IDD_DIALOG_SHOW_ORGINIMG        148
#define IDD_DIALOG_CONFIG_DEFECTCLASS   149
#define IDD_DIALOG_HELP                 150
#define IDC_TAB_MAIN                    1001
#define IDC_TREE_IMAGEPATH              1002
#define IDC_BUTTON_OPENDIR              1003
#define IDC_EDIT_FILEPATH               1004
#define IDC_IMAGESHOW                   1005
#define IDC_COMBO_SEG_SELECT            1006
#define IDC_BUTTON_AUTOSEG              1007
#define IDC_LIST_IMGSAMPLE              1008
#define IDC_EDIT_SAMPLESET_PATH         1010
#define IDC_BUTTON_SAMPLESET_PATH       1011
#define IDC_LOGO                        1012
#define IDC_EDIT_SAMPLEIMGPATH          1013
#define IDC_BUTTON_GET_IMGSAMPLEPATH    1014
#define IDC_CHECK_NORMIMGSIZE           1015
#define IDC_COMBO_IMGSIZE               1016
#define IDC_LIST1                       1019
#define IDC_LIST_SAMPLEIMGSHOW          1019
#define IDC_LIST_TRAIN_IMGSHOW          1019
#define IDC_LIST_TRAINIMGSHOW           1019
#define IDC_LIST_SHOW_LOAD_INFO         1019
#define IDC_LIST_CLASS_FROM_CHOOSE      1019
#define IDC_LIST_SHOW_LOGINFO           1019
#define IDC_PROGRESS_LOADINGSAMPLEIMG   1020
#define IDC_COMBO1                      1021
#define IDC_COMBO_CLASSNUM              1021
#define IDC_COMBO_TRAIN_CLASSNUM        1021
#define IDC_COMBO_DEFECT_DB_IP          1021
#define IDC_COMBO_SVM_CLASSIFIER_KEN    1021
#define IDC_COMBO_TEST_FUNC             1021
#define IDC_BUTTON_LOADING_SAMPLEIMG    1022
#define IDC_LIST_FEAT_FROM_CHOOSE       1023
#define IDC_LIST_FEAT_TO_CHOOSE         1024
#define IDC_COMBO_TEST_CLASSNUM         1025
#define IDC_BUTTON_FEAT_ADD             1028
#define IDC_BUTTON_FEAT_SUB             1029
#define IDC_TAB_CLASSIFIER              1030
#define IDC_BUTTON1                     1031
#define IDC_BUTTON_TRAIN_AND_TEST_CLASSIFIER 1031
#define IDC_BUTTON_CONNECT_DB           1031
#define IDC_BUTTON_CONFIGDEFECTCLASS    1031
#define IDC_BUTTON_CLASS_ADD            1031
#define IDC_CHECK1                      1034
#define IDC_CHECK_AUTO_GET_FEAT         1034
#define IDC_CHECK_OPTIMIZE_PARAM        1034
#define IDC_CHECK_RTREE_CLASSIFIER_PROIOR 1034
#define IDC_EDIT_FEAT_INFO              1035
#define IDC_BUTTON_GET_FEAT             1036
#define IDC_LIST_TESTIMGSHOW            1037
#define IDC_COMBO_TESTSET_PERCENT       1038
#define IDC_BUTTON_TRAIN_CLASSIFIER     1039
#define IDC_BUTTON_TEST_CLASSIFIER      1040
#define IDC_EDIT_BP_CLASSIFIER_FILENAME 1041
#define IDC_EDIT_HIDE_BODE_NUM          1042
#define IDC_EDIT_ITER_NUM               1043
#define IDC_EDIT_EPSILON                1044
#define IDC_EDITSVM_CLASSIFIER_FILENAME 1047
#define IDC_EDIT_SVM_CLASSIFIER_FILENAME 1047
#define IDC_LIST2                       1048
#define IDC_LIST_SHOWINFO               1048
#define IDC_LIST_CLASS_TO_CHOOSE        1048
#define IDC_LIST_DBDATA_1               1048
#define IDC_IMG_SHOW                    1049
#define IDC_COMBO_DB_TYPE               1050
#define IDC_COMBO_DEFECT_IMG_IP         1051
#define IDC_BUTTON2                     1052
#define IDC_BUTTON_CONNECT_IMG          1052
#define IDC_BUTTON_CLASS_SUB            1052
#define IDC_BUTTON_SHOWCLASSIFY_RESULT  1052
#define IDC_BUTTON_OK                   1053
#define IDC_BUTTON_CAN                  1054
#define IDC_BUTTON_CANCEL               1054
#define IDC_STATIC_RESULT               1055
#define IDC_PIC_RESULTSHOW              1056
#define IDC_EDIT1                       1057
#define IDC_EDIT_RESULT_ACCURACY        1057
#define IDC_EDIT_TREE_NUM               1057
#define IDC_EDIT_WEAK_CLASSIFIER_NUM    1057
#define IDC_EDIT_SVM_CLASSIFIER_C       1057
#define IDC_EDIT_CNN_NETFILE            1057
#define IDC_STATIC_DBDATAINFO           1058
#define IDC_LIST_DBDATA_2               1059
#define IDC_EDIT_RTREE_CLASSIFIER_FILENAME 1059
#define IDC_EDIT3                       1059
#define IDC_EDIT_BOOSTING_CLASSIFIER_FILENAME 1059
#define IDC_LIST_DBDATA_3               1060
#define IDC_LIST_DBDATA_4               1061
#define IDC_LIST_DBDATA_5               1062
#define IDC_LIST_DBDATA_6               1063
#define IDC_LIST_DBDATA_7               1064
#define IDC_LIST9                       1065
#define IDC_LIST_DBDATA_8               1065
#define IDC_LIST3                       1066
#define IDC_LIST_SHOW_WARN_INFO         1066
#define IDC_EDIT2                       1067
#define IDC_EDIT_SVM_CLASSIFIER_GAMMA   1067
#define IDC_EDIT_CNN_MODELFILE          1067
#define IDC_STATIC_IMG_POS              1068
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_ADD0                         32774
#define ID_ADD1                         32775
#define ID_ADD2                         32776
#define ID_ADD_NEW                      32777
#define ID_ADDNEW                       32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
